var ALICE = 0;
var BOB = 1;

var ALICETOALICE = 2;
var ALICETOBOB = 3;
var BOBTOBOB = 4
var BOBTOALICE = 5;

var HASHKEYPUBLICALICE = 6;
var HASHKEYPUBLICBOB = 7;

var SCRIPTINPUT = 8;
var SCRIPTOUTPUT = 9;

var HIGH = 33333;
var LOW = 0;
var NUMBER_ZERO = 3;

var TIME_PERIOD = 42218224;

var NB_TRANSACTION_PER_BLOCK = 1;

var QUERY_LATEST = 0;
var QUERY_ALL = 1;
var RESPONSE_BLOCKCHAIN = 2;
var FIND_PROOF = 3;
var PEERS = 4;
var SEND_MY_PORT = 5;

var OTHERNODE = 2;
var MYNODE = 3;

var FIRST_BLOCKCHAIN = 0;

var LISTTRANSACTIONFULL = 1;
var LISTNOTFULL = 0;

var BLOCK_FALSE = -1;
var SAME_INDEX_AND_MORE_RECENT = 0;
var SAME_INDEX_AND_TIMESTAMP = 1;
var BLOCK_TRUE_AND_DIFFERENT_INDEX = 2;

var FORK_BLOCKCHAIN = 0;
var NO_FORK_BLOCKCHAIN = 1;

//var P = 2 ** 256 - 2 ** 32 - 2 ** 9 - 2 ** 8 - 2 ** 7 - 2 ** 6 - 2 ** 4 - 1
var A = 0
var B = 7
var GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
var GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
//G = (GX, GY)
var N = 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

//exports.P = P;

var MONEY_AND_NAME = 0;
var MONEY_AND_NAME_AND_SCRIPT = 1;
var CHECK_INPUT = 1;
var DONT_CHECK_INPUT = 0;

exports.CHECK_INPUT = CHECK_INPUT;
exports.DONT_CHECK_INPUT = DONT_CHECK_INPUT;
exports.MONEY_AND_NAME = MONEY_AND_NAME;
exports.MONEY_AND_NAME_AND_SCRIPT = MONEY_AND_NAME_AND_SCRIPT;
exports.SCRIPTOUTPUT = SCRIPTOUTPUT;
exports.SCRIPTINPUT = SCRIPTINPUT;
exports.HASHKEYPUBLICALICE = HASHKEYPUBLICALICE;
exports.HASHKEYPUBLICBOB = HASHKEYPUBLICBOB;
exports.GX = GX;
exports.GY = GY;
exports.N = N;
exports.BOBTOBOB = BOBTOBOB;
exports.BOBTOALICE = BOBTOALICE;
exports.ALICE = ALICE;
exports.BOB = BOB;
exports.ALICETOBOB = ALICETOBOB;
exports.ALICETOALICE = ALICETOALICE;
exports.TIME_PERIOD = TIME_PERIOD;
exports.FIRST_BLOCKCHAIN = FIRST_BLOCKCHAIN;
exports.FORK_BLOCKCHAIN = FORK_BLOCKCHAIN;
exports.NO_FORK_BLOCKCHAIN = NO_FORK_BLOCKCHAIN;
exports.BLOCK_FALSE = BLOCK_FALSE;
exports.SAME_INDEX_AND_MORE_RECENT = SAME_INDEX_AND_MORE_RECENT;
exports.SAME_INDEX_AND_TIMESTAMP = SAME_INDEX_AND_TIMESTAMP;
exports.BLOCK_TRUE_AND_DIFFERENT_INDEX = BLOCK_TRUE_AND_DIFFERENT_INDEX;
exports.LISTNOTFULL = LISTNOTFULL;
exports.LISTTRANSACTIONFULL = LISTTRANSACTIONFULL;
exports.OTHERNODE = OTHERNODE;
exports.MYNODE = MYNODE;
exports.QUERY_LATEST = QUERY_LATEST;
exports.QUERY_ALL = QUERY_ALL;
exports.RESPONSE_BLOCKCHAIN = RESPONSE_BLOCKCHAIN;
exports.FIND_PROOF = FIND_PROOF;
exports.PEERS = PEERS;
exports.SEND_MY_PORT = SEND_MY_PORT;
//exports.MessageType = MessageType;
exports.NB_TRANSACTION_PER_BLOCK = NB_TRANSACTION_PER_BLOCK;
exports.HIGH = HIGH;
exports.LOW = LOW;
exports.NUMBER_ZERO = NUMBER_ZERO;
exports.LISTTRANSACTIONFULL = LISTTRANSACTIONFULL;